---
- hosts: windows
  tasks:
  - name: Local Users
    win_dsc5:
      resource_name="xGroup"
      ensure="Present"
      GroupName="Administrators"
      members="Administrator,admin2"

  - name: Local Users2
    win_dsc5:
      resource_name="xGroup"
      ensure="Present"
      GroupName="AdministratorsTemp"
      members="admin2"